### ISSUE TITLE
Typo: 20th order filter

### ISSUE THREAD

**Issue by marcschulder** [WimPouw/envisionBOX_modulesWP#1]
The [MergingMultimodal_inPython](https://github.com/WimPouw/envisionBOX_modulesWP/tree/main/MultimodalMerging/MergingMultimodal_inPython.ipynb) notebook has an unfortunate typo in code block 11, which turns the 2nd order filter into a 20th order filter:
```python
merged[cs] = merged[cs].apply(lambda x: butter_it(x=x,sampling_rate=100, order=20, lowpass_cutoff=20))
```

**Comment by WimPouw** [comment]
Whoops! Thanks for this, Marc. I have corrected it.
